### ISSUE TITLE
Объем скачивания FTP

### ISSUE THREAD

**Issue by ARMrus** [Homyakin/ZakupkiParser#5]
Скажите, скачивет ли скрипт за последние даты, или каждый раз для обнавления бД приходится качать полностью все содержимое FTP

**Comment by Homyakin** [comment]
В данный момент выкачивается все содержимое FTP. Скачивание за последние даты будет реализовано после того, как будет сделан парсинг всех папок.

**Comment by ARMrus** [comment]
Не знаю java помог бы...
А сколько в среднем занимает времени обновление БД?

**Comment by Homyakin** [comment]
Полная выгрузка не проводилась, но на регион уходит примерно 30-40 минут

**Comment by ARMrus** [comment]
Возможность выбрать регион в каких параметрах настраивается?

**Comment by Homyakin** [comment]
Выбора региона пока нет. Добавлю в ближайшее время.

**Comment by ARMrus** [comment]
Буду очень благодарен, если сообщите о добовлении выбора региона, либо о готовности загрузки ежедневных обновлений.

**Comment by Homyakin** [comment]
Выбор региона сделан
